server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sigepid_auth}
    username: ${SPRING_DATASOURCE_USERNAME:sigepid}
    password: ${SPRING_DATASOURCE_PASSWORD:sigepid_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:SiGePID_SuperSecretKey_ChangeInProduction_2024}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
