server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sigepid_orders}
    username: ${SPRING_DATASOURCE_USERNAME:sigepid}
    password: ${SPRING_DATASOURCE_PASSWORD:sigepid_secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      catalog-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
